name: Manual Pull Data For Given date range

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start Date'     
        required: true
        default: 'YYYY-MM-DD'
      end:
        description: 'End Date'     
        required: true
        default: 'YYYY-MM-DD'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Execute Script and Push
        run: |
          python main.py ${START_DATE} ${END_DATE}
          git config --global user.name 'dSquadAdmin'
          git config --global user.email 'dSquadAdmin@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add .
          git commit -am "Data updated"
          git push origin master
        env:
          START_DATE: ${{ github.event.inputs.start }}
          END_DATE: ${{ github.event.inputs.end }}

          

