name: Auto Pull Data For Today

on:
  schedule:
    - cron: '15 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Execute Script
        run: |
          python main.py $(date '+%Y-%m-%d') $(date '+%Y-%m-%d')
  
      - name: Commit and Push Files
        run: |
          git config --global user.name 'dSquadAdmin'
          git config --global user.email 'dSquadAdmin@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add .
          git commit -am "Data updated"
          git push
