name: Auto Pull Data For Single Day

on:
  schedule:
    - cron: '15 10 * * 0-4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Execute Script
        run: |
          chmod 777 ./data -R
          python main.py $(date '+%Y-%m-%d') $(date '+%Y-%m-%d')
  
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data for today
          commit_user_name: dSquadAdmin
          commit_user_email: dSquadAdmin@users.noreply.github.com
