on:
  workflow_dispatch:
    inputs:
      startDate:
        description: "Start Date"
        required: true
        default: "warning"
        type: string
      endDate:
        description: "End Date"
        required: true
        default: "warning"
        type: string

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        run: cd ./nepse
      
      - name: fetch data
        run: python main.py ${{ github.event.inputs.startDate }} ${{ github.event.inputs.startDate }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: dsquadadmin
          author_email: keshavbist19@gmail.com
          message: Data upto ${{ github.event.inputs.startDate }}
          add: './data'
